/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/admin/ingestion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Admin Ingestion
         * @description The version's job runs, every user's uploads and snapshots per source (admins).
         */
        get: operations["get_admin_ingestion_api_admin_ingestion_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/admin/jobs/ingest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Run Ingest Job
         * @description Start the version's game data ingest now, as the daily schedule does: the pinned build, unless it is
         *     loaded already (admins). 409 while a run of it is still going, 501 where nothing can start jobs.
         */
        post: operations["run_ingest_job_api_admin_jobs_ingest_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ah-blocked": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Ah Blocked */
        get: operations["get_ah_blocked_api_ah_blocked_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/ah-blocked/{item_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Block Ah
         * @description Never sell `item_id` on the AH: /api/rank and /api/evaluate only vendor or disenchant it.
         */
        put: operations["block_ah_api_ah_blocked__item_id__put"];
        post?: never;
        /**
         * Unblock Ah
         * @description Allow selling `item_id` on the AH again.
         */
        delete: operations["unblock_ah_api_ah_blocked__item_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/characters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Characters */
        get: operations["get_characters_api_characters_get"];
        put?: never;
        post?: never;
        /**
         * Delete Character
         * @description Delete one of your characters (404 if you have none of that realm and name).
         */
        delete: operations["delete_character_api_characters_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description The Firebase project the front end signs in with.
         */
        get: operations["get_config_api_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coverage": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Coverage
         * @description Each named auction house's scans: where uploads are needed. Open to every tier.
         */
        get: operations["get_coverage_api_coverage_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/evaluate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Evaluate
         * @description One recipe as /api/rank would give it (a session of the user's batch of crafts), with the user's
         *     `choices` of sources and exit applied, and for `copies` crafts or in `city` if given. With `chain_at`, a
         *     run of `chain_from`'s chain, as /api/rank's `chain` has it (or for `copies` crafts at the skill it starts
         *     from).
         */
        post: operations["evaluate_api_evaluate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Event
         * @description Note that something happened in the front end: one JSON log line, anonymous.
         */
        post: operations["post_event_api_events_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Favorites */
        get: operations["get_favorites_api_favorites_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/favorites/{recipe_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Add Favorite
         * @description Mark `recipe_id` as a favorite: /api/rank lists it first.
         */
        put: operations["add_favorite_api_favorites__recipe_id__put"];
        post?: never;
        /**
         * Remove Favorite
         * @description Unmark `recipe_id` as a favorite.
         */
        delete: operations["remove_favorite_api_favorites__recipe_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Me */
        get: operations["get_me_api_me_get"];
        put?: never;
        post?: never;
        /**
         * Delete Me
         * @description Delete your account: your characters, settings, AH blocks and upload history, then the
         *     sign-in account itself. Prices you uploaded stay in the pool, no longer linked to you.
         */
        delete: operations["delete_me_api_me_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/professions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Professions
         * @description Every profession the game version's recipes belong to, by name.
         */
        get: operations["get_professions_api_professions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/rank": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Rank
         * @description What the selected realm/faction's characters can craft, the user's favorites first (not with
         *     `sort=skill`), then most profitable first (each a session of the user's batch of crafts, or with
         *     `sort=rate` per hour of play in the user's city, or with `sort=skill` cheapest expected skill point first
         *     (`skill_ups`), those that give none last); without characters, every recipe, crafted by one unnamed
         *     character (nothing is mailed). Bounds are inclusive and on the session's numbers; an omitted bound is
         *     unbounded (so losses are included unless `min_profit` is set).
         */
        get: operations["get_rank_api_rank_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/selection": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Put Selection
         * @description Switch realm/faction.
         */
        put: operations["put_selection_api_selection_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Status
         * @description Counts, the selection and the versions the front end polls to notice uploads and merges.
         */
        get: operations["get_status_api_status_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/time": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Time
         * @description The user's time settings: the cities the selection's faction crafts in, the one plans are timed
         *     in, and the seconds per action.
         */
        get: operations["get_time_api_time_get"];
        /**
         * Put Time
         * @description Save the user's city (None: the faction's default) and time settings (those not given are reset
         *     to the defaults); 400 for an unknown city or a bad setting.
         */
        put: operations["put_time_api_time_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Uploads
         * @description Your newest uploads (every game version), newest first.
         */
        get: operations["get_uploads_api_uploads_get"];
        put?: never;
        /**
         * Post Upload
         * @description Import an addon's SavedVariables file (plain or gzipped). Alt Army replaces your characters of this
         *     game version and, on WoW: Forever, records the auction house scans the addon took. An Auctionator file
         *     is refused (400) where prices come from those scans alone.
         */
        post: operations["post_upload_api_uploads_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/uploads/paste": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Paste
         * @description Import the Alt Army addon's export string: replaces your characters of this game version, as an
         *     AltArmy_TBC.lua upload would. 400 if it is damaged or from the other game's client.
         */
        post: operations["post_paste_api_uploads_paste_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Versions
         * @description The game versions served, each with the build its data comes from.
         */
        get: operations["get_versions_api_versions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminUploadOut */
        AdminUploadOut: {
            /** Detail */
            detail: string;
            /** Game Version */
            game_version: string;
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "altarmy" | "auctionator";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "accepted" | "rejected";
            /** Received At */
            received_at: string;
            /** Size */
            size: number;
            /** User Uid */
            user_uid: string;
            /**
             * Via
             * @enum {string}
             */
            via: "browser" | "watcher" | "paste";
        };
        /**
         * AhBlocked
         * @description Items never sold on the AH: only vendored or disenchanted.
         */
        AhBlocked: {
            /** Details */
            details: {
                [key: string]: components["schemas"]["ItemInfo"];
            };
            /** Items */
            items: components["schemas"]["AhBlockedItem"][];
        };
        /** AhBlockedItem */
        AhBlockedItem: {
            /** Added At */
            added_at: string;
            /** Item Id */
            item_id: number;
        };
        /** Body_post_upload_api_uploads_post */
        Body_post_upload_api_uploads_post: {
            /** File */
            file: string;
            /**
             * Kind
             * @enum {string}
             */
            kind: "altarmy" | "auctionator";
            /**
             * Modified At
             * @description the file's modified time, ms since 1970
             */
            modified_at?: number | null;
            /**
             * Via
             * @default browser
             * @enum {string}
             */
            via: "browser" | "watcher";
        };
        /** CharacterOut */
        CharacterOut: {
            /** Class File */
            class_file: string;
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Professions */
            professions: components["schemas"]["ProfessionOut"][];
            /**
             * Talents
             * @default []
             */
            talents: components["schemas"]["TalentOut"][];
            /**
             * Vendor Discounts
             * @default []
             */
            vendor_discounts: components["schemas"]["VendorDiscountOut"][];
        };
        /** Characters */
        Characters: {
            /**
             * Arcane Salvager
             * @default false
             */
            arcane_salvager: boolean;
            /** Auto Import At */
            auto_import_at?: string | null;
            /** Groups */
            groups: components["schemas"]["GroupOut"][];
            /** Imported At */
            imported_at?: string | null;
            /** Imported Via */
            imported_via?: ("browser" | "watcher" | "paste") | null;
            selection: components["schemas"]["SelectionModel"] | null;
        };
        /** CityOut */
        CityOut: {
            /** Faction */
            faction: string;
            /** Hub */
            hub: string;
            /** Locations */
            locations: number;
            /** Name */
            name: string;
            /** Vendors */
            vendors: number;
        };
        /**
         * CityTimingOut
         * @description The result in one city: as planned there when the cities were compared, else (the user's city is
         *     set, or `city` was asked for) its plan with the vendor buys at that city's prices.
         */
        CityTimingOut: {
            /** City */
            city: string;
            /** Missing */
            missing: string[];
            /** Per Hour */
            per_hour: number;
            /** Profit */
            profit: number;
            /** Total Seconds */
            total_seconds: number;
        };
        /**
         * ConfidenceOut
         * @description How far a result's AH sell price can be trusted (`prices.confidence`), and the numbers behind it.
         */
        ConfidenceOut: {
            /**
             * Flags
             * @default []
             */
            flags: ("lone" | "thin" | "sold_out" | "unlisted" | "few_days" | "unwatched" | "one_pair")[];
            /**
             * Level
             * @enum {string}
             */
            level: "high" | "medium" | "low";
            /** Listed */
            listed: number | null;
            /**
             * Reason
             * @enum {string}
             */
            reason: "hand_set" | "sold" | "few_sold" | "one_pair" | "unlisted" | "few_days" | "unsold" | "unwatched" | "thin";
            /** Scan Days */
            scan_days: number;
            /** Sold */
            sold: number;
            /**
             * Sold Pairs
             * @default 0
             */
            sold_pairs: number;
            /** Units */
            units: number;
            /** Unlisted Since */
            unlisted_since: string | null;
            /** Watched Hours */
            watched_hours: number;
        };
        /** ConfigOut */
        ConfigOut: {
            firebase: components["schemas"]["FirebaseOut"];
        };
        /**
         * CoverageOut
         * @description How well one auction house is scanned, so uploaders see where scans are needed.
         */
        CoverageOut: {
            /** Auction House Id */
            auction_house_id: number;
            /** Faction */
            faction: string;
            /** Last Scan */
            last_scan: string | null;
            /** Last Scan Items */
            last_scan_items: number;
            /** Prices */
            prices: number;
            /** Realm */
            realm: string;
            /** Scans 7D */
            scans_7d: number;
            /** Uploaders 7D */
            uploaders_7d: number;
            /**
             * Watched Hours
             * @default 0
             */
            watched_hours: number;
        };
        /**
         * DetailOut
         * @description One line of a session spelled out.
         */
        DetailOut: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "switch" | "start" | "go" | "step";
            location: components["schemas"]["LocationOut"] | null;
            /** Retrieve */
            retrieve: components["schemas"]["ItemCount"][];
            /** Seconds */
            seconds: number;
            /** Step */
            step: number | null;
            /** Who */
            who: string;
        };
        /**
         * EffectOut
         * @description A green tooltip line.
         */
        EffectOut: {
            /** Text */
            text: string;
            /** Trigger */
            trigger: string;
        };
        /**
         * EvaluateRequest
         * @description Re-cost one recipe with some of its sources or its exit picked by the user.
         */
        EvaluateRequest: {
            /**
             * Arcane Salvager
             * @default false
             */
            arcane_salvager: boolean;
            /** Chain At */
            chain_at?: number | null;
            /** Chain From */
            chain_from?: number | null;
            /** Choices */
            choices: {
                [key: string]: string;
            };
            /** City */
            city?: string | null;
            /**
             * Climb Without
             * @default []
             */
            climb_without: number[];
            /** Climber Skill */
            climber_skill?: number | null;
            /** Copies */
            copies?: number | null;
            /** Crafter */
            crafter?: string | null;
            /**
             * Effort
             * @default balanced
             * @enum {string}
             */
            effort: "cheapest" | "balanced" | "fewest";
            /**
             * Exits
             * @default [
             *       "vendor",
             *       "ah",
             *       "disenchant"
             *     ]
             */
            exits: ("vendor" | "ah" | "disenchant" | "skill" | "keep")[];
            /**
             * Gathered
             * @default []
             */
            gathered: number[];
            /**
             * Include Trivial
             * @default true
             */
            include_trivial: boolean;
            /**
             * Look Ahead
             * @default 0
             */
            look_ahead: number;
            /** Price Version */
            price_version?: number | null;
            /** Recipe Id */
            recipe_id: number;
            /**
             * Runs
             * @default false
             */
            runs: boolean;
            /**
             * Skill Crafters
             * @default []
             */
            skill_crafters: string[];
            /**
             * Sources
             * @default [
             *       "trainer",
             *       "recipe"
             *     ]
             */
            sources: ("trainer" | "recipe" | "bop")[];
            /**
             * Unlearned
             * @default none
             * @enum {string}
             */
            unlearned: "none" | "train" | "all";
        };
        /** EvaluateResponse */
        EvaluateResponse: {
            /** Items */
            items: {
                [key: string]: components["schemas"]["ItemInfo"];
            };
            result: components["schemas"]["RankResult"];
            /**
             * Watched Hours
             * @default 0
             */
            watched_hours: number;
        };
        /** EventIn */
        EventIn: {
            /**
             * Name
             * @enum {string}
             */
            name: "aim_chosen" | "next_up_shown" | "row_opened" | "copy_steps" | "gather_toggled" | "coach_shown";
            /**
             * Props
             * @default {}
             */
            props: {
                [key: string]: string | number | boolean;
            };
        };
        /** ExitOut */
        ExitOut: {
            /** Kind */
            kind: string;
            /** Mail To */
            mail_to: string;
            /** Materials */
            materials: components["schemas"]["MaterialOut"][];
            /** Postage */
            postage: number;
            /** Value */
            value: number;
        };
        /** FavoriteRecipe */
        FavoriteRecipe: {
            /** Added At */
            added_at: string;
            /** Recipe Id */
            recipe_id: number;
        };
        /**
         * Favorites
         * @description Recipes the user marked as favorites: /api/rank lists them first.
         */
        Favorites: {
            /** Recipes */
            recipes: components["schemas"]["FavoriteRecipe"][];
        };
        /**
         * FirebaseOut
         * @description The Firebase web config the front end signs in with (public values).
         */
        FirebaseOut: {
            /** Api Key */
            api_key: string;
            /** Auth Domain */
            auth_domain: string;
            /** Emulator Url */
            emulator_url: string | null;
            /** Firestore Emulator Host */
            firestore_emulator_host?: string | null;
            /** Project Id */
            project_id: string;
        };
        /** GroupCount */
        GroupCount: {
            /** Characters */
            characters: number;
            /** Faction */
            faction: string;
            /** Realm */
            realm: string;
        };
        /** GroupOut */
        GroupOut: {
            /** Characters */
            characters: components["schemas"]["CharacterOut"][];
            /** Faction */
            faction: string;
            /** Realm */
            realm: string;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionOut
         * @description What the ingestion jobs and uploads have been doing (the Admin page).
         */
        IngestionOut: {
            /** Can Run */
            can_run: string[];
            /** Jobs */
            jobs: components["schemas"]["JobStatusOut"][];
            /** Now */
            now: string;
            /** Runs */
            runs: components["schemas"]["JobRunOut"][];
            /** Snapshots */
            snapshots: components["schemas"]["SnapshotStatsOut"][];
            uploads: components["schemas"]["UploadStatsOut"];
        };
        /** ItemCount */
        ItemCount: {
            /** Count */
            count: number;
            /** Item Id */
            item_id: number;
        };
        /**
         * ItemInfo
         * @description Everything an item tooltip shows.
         */
        ItemInfo: {
            /**
             * Ah Levels
             * @default []
             */
            ah_levels: components["schemas"]["LevelOut"][];
            /** Ah Price */
            ah_price: number | null;
            /** Ah Quantity */
            ah_quantity: number | null;
            /** Ah Sell Price */
            ah_sell_price: number | null;
            /** Armor */
            armor: number;
            /** Bonding */
            bonding: number;
            /** Class Id */
            class_id: number;
            /** Container Slots */
            container_slots: number;
            /** Description */
            description: string | null;
            /** Dmg Max */
            dmg_max: number;
            /** Dmg Min */
            dmg_min: number;
            /** Dps */
            dps: number;
            /** Effects */
            effects: components["schemas"]["EffectOut"][];
            /** Icon */
            icon: string | null;
            /** Id */
            id: number;
            /** Inventory Type */
            inventory_type: number;
            /** Item Delay */
            item_delay: number;
            /** Listed */
            listed?: boolean | null;
            /** Market Price */
            market_price?: number | null;
            /** Median 7D */
            median_7d?: number | null;
            /** Name */
            name: string;
            /** Quality */
            quality: number;
            /** Required Level */
            required_level: number;
            /** Required Skill */
            required_skill: string | null;
            /** Required Skill Rank */
            required_skill_rank: number;
            /** Sale Price */
            sale_price?: number | null;
            /** Scans 7D */
            scans_7d?: number | null;
            /** Seen At */
            seen_at?: string | null;
            /** Sell Price */
            sell_price: number;
            /**
             * Sold 7D
             * @default 0
             */
            sold_7d: number;
            /** Sold Pairs 7D */
            sold_pairs_7d?: number | null;
            /**
             * Stack Size
             * @default 1
             */
            stack_size: number;
            /** Stats */
            stats: string[];
            /** Subclass Name */
            subclass_name: string | null;
            /** Vendor Price */
            vendor_price: number | null;
        };
        /** JobRunOut */
        JobRunOut: {
            /** Finished At */
            finished_at: string | null;
            /** Game Version */
            game_version: string | null;
            /** Id */
            id: number;
            /** Job */
            job: string;
            /** Ok */
            ok: boolean | null;
            /** Started At */
            started_at: string;
            /** Summary */
            summary: string;
        };
        /** JobStartedOut */
        JobStartedOut: {
            /** Detail */
            detail: string;
            /** Game Version */
            game_version: string;
            /** Job */
            job: string;
        };
        /**
         * JobStatusOut
         * @description A scheduled job's newest run (every field but `job` and `late` None if it never ran).
         */
        JobStatusOut: {
            /** Game Version */
            game_version: string | null;
            /** Job */
            job: string;
            /** Last Finished */
            last_finished: string | null;
            /** Last Started */
            last_started: string | null;
            /** Late */
            late: boolean;
            /** Ok */
            ok: boolean | null;
            /** Summary */
            summary: string;
        };
        /**
         * LearnOut
         * @description Where to learn a recipe nobody has learned.
         */
        LearnOut: {
            /** Items */
            items: components["schemas"]["RecipeItemOut"][];
            /** Profession */
            profession: string;
            /** Skill */
            skill: number;
            /**
             * Source
             * @enum {string}
             */
            source: "trainer" | "recipe" | "bop";
            /**
             * Train Cost
             * @default 0
             */
            train_cost: number;
        };
        /**
         * LegOut
         * @description One run across the city.
         */
        LegOut: {
            /** From Id */
            from_id: string;
            /** From Name */
            from_name: string;
            /** Seconds */
            seconds: number;
            /** To Id */
            to_id: string;
            /** To Name */
            to_name: string;
            /** Who */
            who: string;
        };
        /**
         * LevelOut
         * @description The units listed at one unit price.
         */
        LevelOut: {
            /** Age */
            age: number;
            /** Counted */
            counted: boolean;
            /** Listings */
            listings: number;
            /** More */
            more: boolean;
            /** Price */
            price: number;
            /** Quantity */
            quantity: number;
        };
        /** LocationOut */
        LocationOut: {
            /** Id */
            id: string;
            /** Kind */
            kind: string;
            /** Map Area */
            map_area: number | null;
            /** Map X */
            map_x: number | null;
            /** Map Y */
            map_y: number | null;
            /** Name */
            name: string;
        };
        /**
         * MaterialOut
         * @description One possible disenchant result.
         */
        MaterialOut: {
            /** Chance */
            chance: number;
            /** Expected */
            expected: number;
            /** Item Id */
            item_id: number;
            /** Max Count */
            max_count: number;
            /** Min Count */
            min_count: number;
            /** Name */
            name: string;
            /** Value */
            value: number | null;
        };
        /** Me */
        Me: {
            /** Admin */
            admin: boolean;
            /**
             * Tier
             * @enum {string}
             */
            tier: "free" | "linked";
            /** Uid */
            uid: string;
        };
        /**
         * MilestoneOut
         * @description What a climb is expected to come to by the time it reaches `skill`: its crafts (spent less what
         *     selling what they make brings back, so negative when they earn) and its patterns, `unknown` of which have
         *     no known price (not counted).
         */
        MilestoneOut: {
            /** Cost */
            cost: number;
            /** Skill */
            skill: number;
            /**
             * Unknown
             * @default 0
             */
            unknown: number;
        };
        /**
         * NodeOut
         * @description One item in a craft's reagent tree: bought (no inputs) or crafted from its inputs, possibly by
         *     another character who then mails it on.
         */
        NodeOut: {
            /**
             * Convert
             * @default false
             */
            convert: boolean;
            /** Cost */
            cost: number;
            /** Crafter */
            crafter: string;
            /** Crafts */
            crafts: number;
            /**
             * Discount
             * @default 0
             */
            discount: number;
            /**
             * Enchant
             * @default false
             */
            enchant: boolean;
            /**
             * Flip
             * @default false
             */
            flip: boolean;
            /** Inputs */
            inputs: components["schemas"]["NodeOut"][];
            /** Item Id */
            item_id: number;
            /** Made */
            made: number;
            /** Mail To */
            mail_to: string;
            /** Name */
            name: string;
            /** Option */
            option: string;
            /** Options */
            options: components["schemas"]["OptionOut"][];
            /** Postage */
            postage: number;
            /** Quantity */
            quantity: number;
            /**
             * Rep Discount
             * @default 0
             */
            rep_discount: number;
            /**
             * Rep Faction
             * @default
             */
            rep_faction: string;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
            /**
             * Short
             * @default 0
             */
            short: number;
            /** Source */
            source: string;
            /** Via */
            via: string;
        };
        /**
         * OptionOut
         * @description One way to get a node's items; POST it back as a choice by `key`.
         */
        OptionOut: {
            /**
             * Convert
             * @default false
             */
            convert: boolean;
            /** Cost */
            cost: number;
            /** Crafter */
            crafter: string;
            /** Key */
            key: string;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
            /** Source */
            source: string;
            /** Via */
            via: string;
        };
        /** PasteRequest */
        PasteRequest: {
            /** Text */
            text: string;
        };
        /**
         * PlaceOut
         * @description Somewhere a recipe item comes from (vanilla's world data: Forever may differ).
         */
        PlaceOut: {
            /**
             * Area
             * @default 0
             */
            area: number;
            /** Chance */
            chance: number;
            /** Count */
            count: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "vendor" | "drop" | "object" | "container" | "world_drop" | "quest" | "more";
            /** Levels */
            levels: string;
            /** Limited */
            limited: boolean;
            /**
             * Map X
             * @default 0
             */
            map_x: number;
            /**
             * Map Y
             * @default 0
             */
            map_y: number;
            /** Name */
            name: string;
            /**
             * Side
             * @enum {string}
             */
            side: "alliance" | "horde" | "";
            /** Zone */
            zone: string;
        };
        /** ProfessionOut */
        ProfessionOut: {
            /** Max Rank */
            max_rank: number;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Recipes */
            recipes: number;
        };
        /**
         * ProfessionRankOut
         * @description A profession rank: taught from `train_at` skill and character `level`, the skill goes up to `cap`.
         */
        ProfessionRankOut: {
            /** Cap */
            cap: number;
            /** Level */
            level: number;
            /** Name */
            name: string;
            /** Train At */
            train_at: number;
        };
        /** RankResponse */
        RankResponse: {
            /**
             * Chain
             * @default []
             */
            chain: components["schemas"]["RankResult"][];
            chain_start?: components["schemas"]["RankResult"] | null;
            /** Classes */
            classes: {
                [key: string]: string;
            };
            /** Items */
            items: {
                [key: string]: components["schemas"]["ItemInfo"];
            };
            /**
             * Learn
             * @default {}
             */
            learn: {
                [key: string]: components["schemas"]["LearnOut"];
            };
            /**
             * Option Chains
             * @default []
             */
            option_chains: components["schemas"]["RankResult"][][];
            /**
             * Options
             * @default []
             */
            options: components["schemas"]["RankResult"][];
            /** Results */
            results: components["schemas"]["RankResult"][];
            /** Total */
            total: number;
            /**
             * Watched Hours
             * @default 0
             */
            watched_hours: number;
        };
        /** RankResult */
        RankResult: {
            /**
             * Ah Depth Units
             * @default 0
             */
            ah_depth_units: number;
            /**
             * Ah Excess Units
             * @default 0
             */
            ah_excess_units: number;
            /** Ah Profit */
            ah_profit?: number | null;
            /** Best City */
            best_city?: string | null;
            /** Best Exit */
            best_exit: string;
            /**
             * Bonus Output
             * @default 0
             */
            bonus_output: number;
            /**
             * Buy Flags
             * @default []
             */
            buy_flags: string[];
            /**
             * Cities
             * @default []
             */
            cities: components["schemas"]["CityTimingOut"][];
            /** Climb Cost */
            climb_cost?: number | null;
            /**
             * Climb End
             * @default 0
             */
            climb_end: number;
            /**
             * Climb Unknown
             * @default 0
             */
            climb_unknown: number;
            /**
             * Climb Without
             * @default []
             */
            climb_without: number[];
            confidence?: components["schemas"]["ConfidenceOut"] | null;
            /** Cost */
            cost: number;
            /** Crafter */
            crafter: string;
            /** Crafters */
            crafters: string[];
            /**
             * Crafts
             * @default 1
             */
            crafts: number;
            /**
             * Crafts P80
             * @default 0
             */
            crafts_p80: number;
            /** Days To Sell */
            days_to_sell: number | null;
            /**
             * Depth Units
             * @default 0
             */
            depth_units: number;
            /**
             * Details
             * @default []
             */
            details: components["schemas"]["DetailOut"][];
            /**
             * Excess Units
             * @default 0
             */
            excess_units: number;
            /** Exits */
            exits: components["schemas"]["ExitOut"][];
            /**
             * Kind
             * @default craft
             * @enum {string}
             */
            kind: "craft" | "convert" | "flip" | "enchant";
            /**
             * Learn Cost
             * @default 0
             */
            learn_cost: number | null;
            /**
             * Learn Skill
             * @default 0
             */
            learn_skill: number;
            /** Likely Exit */
            likely_exit: string;
            /** Likely Profit */
            likely_profit: number;
            /** Mail To */
            mail_to: string;
            /**
             * Milestones
             * @default []
             */
            milestones: components["schemas"]["MilestoneOut"][];
            /** Output Count */
            output_count: number;
            /** Output Item Id */
            output_item_id: number;
            /** Output Name */
            output_name: string;
            /**
             * Overtaken By
             * @default
             */
            overtaken_by: string;
            /**
             * Overtaken By Item
             * @default 0
             */
            overtaken_by_item: number;
            /** Point Crafts */
            point_crafts?: number[];
            /** Postage */
            postage: number;
            /** Profession */
            profession: string;
            /** Profit */
            profit: number;
            /** Reach Chances */
            reach_chances?: number[];
            /** Reagents */
            reagents: components["schemas"]["ItemCount"][];
            /** Recipe */
            recipe: string;
            /** Recipe Id */
            recipe_id: number;
            /** Revenue */
            revenue: number;
            /** Roi */
            roi: number;
            /** Safe Exit */
            safe_exit?: string | null;
            /** Safe Profit */
            safe_profit?: number | null;
            /** Sell Options */
            sell_options: components["schemas"]["SellOptionOut"][];
            /** Short */
            short: number;
            /** Skill Chance */
            skill_chance: number;
            /** Skill Ups */
            skill_ups: number;
            /**
             * Skill Ups Bonus
             * @default 0
             */
            skill_ups_bonus: number;
            /** Slow */
            slow: boolean;
            /** Steps */
            steps: components["schemas"]["StepOut"][];
            /**
             * Stop Reason
             * @default
             */
            stop_reason: string;
            /**
             * Stop Skill
             * @default 0
             */
            stop_skill: number;
            timing?: components["schemas"]["TimingOut"] | null;
            tree: components["schemas"]["NodeOut"];
            /**
             * Trivial High
             * @default 0
             */
            trivial_high: number;
            /**
             * Trivial Low
             * @default 0
             */
            trivial_low: number;
        };
        /** RealmPricesOut */
        RealmPricesOut: {
            /** Auction House Id */
            auction_house_id: number;
            /** Faction */
            faction: string;
            /** Items */
            items: number;
            /** Key */
            key: string;
            /** Moved */
            moved: number;
            /** Quarantined */
            quarantined: boolean;
            /** Realm */
            realm: string;
        };
        /** RecipeItemOut */
        RecipeItemOut: {
            /** Item Id */
            item_id: number;
            /**
             * Limited
             * @default false
             */
            limited: boolean;
            /** Name */
            name: string;
            /** Places */
            places: components["schemas"]["PlaceOut"][];
            /** Price */
            price?: number | null;
        };
        /**
         * SelectionModel
         * @description A realm and faction: whose recipes count and which auction house prices them.
         */
        SelectionModel: {
            /** Faction */
            faction: string;
            /** Realm */
            realm: string;
        };
        /** SellOptionOut */
        SellOptionOut: {
            /** Kind */
            kind: string;
            /** Profit */
            profit: number;
        };
        /** SnapshotStatsOut */
        SnapshotStatsOut: {
            /** Items 7D */
            items_7d: number;
            /** Newest Received At */
            newest_received_at: string;
            /** Quarantined 7D */
            quarantined_7d: number;
            /** Snapshots 24H */
            snapshots_24h: number;
            /** Snapshots 7D */
            snapshots_7d: number;
            /** Source */
            source: string;
        };
        /** Status */
        Status: {
            /** Auction House Id */
            auction_house_id: number | null;
            /** Build */
            build: string | null;
            /** Characters */
            characters: number;
            /** Data Version */
            data_version: number;
            /** Items */
            items: number;
            /** Price Version */
            price_version: number | null;
            /** Prices */
            prices: number;
            /** Recipes */
            recipes: number;
            selection: components["schemas"]["SelectionModel"] | null;
        };
        /** StepOut */
        StepOut: {
            /**
             * Action
             * @enum {string}
             */
            action: "buy" | "gather" | "craft" | "mail" | "sell";
            /**
             * Bonus
             * @default 0
             */
            bonus: number;
            /**
             * Convert
             * @default false
             */
            convert: boolean;
            /**
             * Discount
             * @default 0
             */
            discount: number;
            /**
             * Enchant
             * @default false
             */
            enchant: boolean;
            /** Item Id */
            item_id: number;
            /**
             * Lead Seconds
             * @default 0
             */
            lead_seconds: number;
            /** Name */
            name: string;
            /** Paths */
            paths: string[];
            /** Quantity */
            quantity: number;
            /**
             * Rep Discount
             * @default 0
             */
            rep_discount: number;
            /**
             * Rep Faction
             * @default
             */
            rep_faction: string;
            /**
             * Seconds
             * @default 0
             */
            seconds: number;
            /**
             * Station
             * @default
             */
            station: string;
            /** Value */
            value: number;
            /** Via */
            via: string;
            /** Who */
            who: string;
        };
        /**
         * TalentOut
         * @description A Legacy talent (WoW: Forever) that changes profits.
         */
        TalentOut: {
            /** Max Rank */
            max_rank: number;
            /** Name */
            name: string;
            /** Rank */
            rank: number;
            /** Spell Id */
            spell_id: number;
        };
        /**
         * TimeConfigModel
         * @description Seconds per action, crafts per session, what an hour of play is worth (copper) and running speed.
         */
        TimeConfigModel: {
            /** Ah Buy */
            ah_buy: number;
            /** Ah Post */
            ah_post: number;
            /** Ah Search */
            ah_search: number;
            /** Batch */
            batch: number;
            /** Craft Overhead */
            craft_overhead: number;
            /** Detour */
            detour: number;
            /** Disenchant */
            disenchant: number;
            /** Mail Attach */
            mail_attach: number;
            /** Mail Attachments */
            mail_attachments: number;
            /** Mail Open */
            mail_open: number;
            /** Mail Send */
            mail_send: number;
            /** Run Speed */
            run_speed: number;
            /** Switch Character */
            switch_character: number;
            /** Time Value */
            time_value: number;
            /** Vendor Buy */
            vendor_buy: number;
            /** Vendor Sell */
            vendor_sell: number;
        };
        /** TimeSettings */
        TimeSettings: {
            /** Active */
            active: string | null;
            /** Cities */
            cities: components["schemas"]["CityOut"][];
            /** City */
            city: string | null;
            config: components["schemas"]["TimeConfigModel"];
            defaults: components["schemas"]["TimeConfigModel"];
        };
        /** TimeSettingsIn */
        TimeSettingsIn: {
            /** City */
            city?: string | null;
            /**
             * Config
             * @default {}
             */
            config: {
                [key: string]: number;
            };
        };
        /**
         * TimingOut
         * @description How long the result's session (its `crafts`) takes in a city, and what that makes per hour.
         */
        TimingOut: {
            /** Breakdown */
            breakdown: {
                [key: string]: number;
            };
            /** City */
            city: string;
            /** Deployed */
            deployed: string[];
            /** Fixed Seconds */
            fixed_seconds: number;
            /** Legs */
            legs: components["schemas"]["LegOut"][];
            /** Missing */
            missing: string[];
            /** Per Craft Seconds */
            per_craft_seconds: number;
            /** Per Hour */
            per_hour: number;
            /** Total Seconds */
            total_seconds: number;
            /** Unsold */
            unsold: number[];
        };
        /** UploadOut */
        UploadOut: {
            /** Detail */
            detail: string;
            /** Game Version */
            game_version: string;
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "altarmy" | "auctionator";
            /**
             * Outcome
             * @enum {string}
             */
            outcome: "accepted" | "rejected";
            /** Received At */
            received_at: string;
            /** Size */
            size: number;
            /**
             * Via
             * @enum {string}
             */
            via: "browser" | "watcher" | "paste";
        };
        /** UploadResult */
        UploadResult: {
            /** Characters */
            characters: number;
            /** Detail */
            detail: string;
            /** Groups */
            groups: components["schemas"]["GroupCount"][];
            /**
             * Kind
             * @enum {string}
             */
            kind: "altarmy" | "auctionator";
            /** Realms */
            realms: components["schemas"]["RealmPricesOut"][];
        };
        /** UploadStatsOut */
        UploadStatsOut: {
            /** Accepted 24H */
            accepted_24h: number;
            /** Accepted 7D */
            accepted_7d: number;
            /** Recent */
            recent: components["schemas"]["AdminUploadOut"][];
            /** Rejected 24H */
            rejected_24h: number;
            /** Rejected 7D */
            rejected_7d: number;
            /** Uploaders 7D */
            uploaders_7d: number;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /**
         * VendorDiscountOut
         * @description What a character's reputation takes off at a city faction's vendors.
         */
        VendorDiscountOut: {
            /** Faction */
            faction: string;
            /** Percent */
            percent: number;
        };
        /**
         * VersionOut
         * @description A game version the app serves; pass its `key` as `game_version` to the other routes.
         */
        VersionOut: {
            /** Ah Cut */
            ah_cut: number;
            /** Build */
            build: string | null;
            /**
             * Key
             * @enum {string}
             */
            key: "tbc" | "forever";
            /** Label */
            label: string;
            /** Profession Ranks */
            profession_ranks: components["schemas"]["ProfessionRankOut"][];
            /** Recipes */
            recipes: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_admin_ingestion_api_admin_ingestion_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    run_ingest_job_api_admin_jobs_ingest_post: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStartedOut"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_ah_blocked_api_ah_blocked_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AhBlocked"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    block_ah_api_ah_blocked__item_id__put: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AhBlocked"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    unblock_ah_api_ah_blocked__item_id__delete: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path: {
                item_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AhBlocked"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_characters_api_characters_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Characters"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_character_api_characters_delete: {
        parameters: {
            query: {
                realm: string;
                name: string;
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Characters"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigOut"];
                };
            };
        };
    };
    get_coverage_api_coverage_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoverageOut"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    evaluate_api_evaluate_post: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EvaluateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EvaluateResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_event_api_events_post: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EventIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_favorites_api_favorites_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorites"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    add_favorite_api_favorites__recipe_id__put: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorites"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_favorite_api_favorites__recipe_id__delete: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path: {
                recipe_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Favorites"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_me_api_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Me"];
                };
            };
        };
    };
    delete_me_api_me_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    get_professions_api_professions_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_rank_api_rank_get: {
        parameters: {
            query: {
                /** @description recipes nobody has learned: none, those a character can train (see `look_ahead` and `sources`), or every recipe of their professions (all) */
                unlearned?: "none" | "train" | "all";
                /** @description with unlearned=train: how much more skill than a character has a recipe may need (0: only what they can train now) */
                look_ahead?: number;
                /** @description with unlearned=train: what may teach the recipe: a trainer, a recipe item that can be traded (recipe), one that binds on pickup (bop) */
                sources?: ("trainer" | "recipe" | "bop")[];
                /** @description also recipes that can't give the crafter a skillup (grey or at the cap) */
                include_trivial?: boolean;
                /** @description the characters being skilled up: the final craft is done only by one of them, the lowest-skilled in the recipe's profession (default: anyone) */
                skill_crafters?: string[] | null;
                /** @description ways the crafts may be sold */
                exits?: ("vendor" | "ah" | "disenchant" | "skill" | "keep")[];
                /** @description disenchant at an Arcane Salvager: a 10% chance of a second disenchant's materials */
                arcane_salvager?: boolean;
                /** @description copper */
                min_cost?: number | null;
                /** @description copper */
                max_cost?: number | null;
                /** @description copper */
                min_profit?: number | null;
                /** @description copper */
                max_profit?: number | null;
                /** @description profit / cost (0.5 = 50%) */
                min_roi?: number | null;
                /** @description profit / cost (0.5 = 50%) */
                max_roi?: number | null;
                /** @description only AH sales whose sell price is trusted at least this much (others all pass) */
                min_confidence?: ("high" | "medium" | "low") | null;
                /** @description only recipes of these professions (default: every one) */
                professions?: string[] | null;
                /** @description profit per session (the batch; all_sell is the same), per hour of play, cheapest skill point, likely profit (`likely_profit`), ROI, least spent, profit per unit made, or the profit selling it all safely (a vendor or disenchanting: `safe`) or on the auction house (`ah`), those it isn't open to last */
                sort?: "profit" | "rate" | "skill" | "likely" | "all_sell" | "roi" | "spend" | "profit_each" | "safe" | "ah";
                /** @description `safe` and `ah` only: best first, or worst first (those not open to it last) */
                order?: "desc" | "asc";
                /** @description items the user gathers: had for what selling them would make, instead of bought */
                gathered?: number[] | null;
                /** @description with skill_crafters: rank each recipe as a run, the crafts until another recipe would give the one skilled up a cheaper skill point, not as the user's batch */
                runs?: boolean;
                /** @description with runs: how a climb weighs crafts against copper (`CRAFT_VALUES`): cheapest counts copper alone, fewest crafts values each at 2s */
                effort?: "cheapest" | "balanced" | "fewest";
                top?: number;
                /** @description the auction house's price version the front end knows of */
                price_version?: number | null;
                /** @description with sort=skill and runs: the recipe whose run the chain follows (default the first) */
                chain_from?: number | null;
                /** @description with sort=skill and runs: the runs the chain may hold */
                chain_length?: number;
                /** @description rank for a character nobody uploaded instead of the selection's: the one name in skill_crafters, with the one profession in professions at this skill, knowing what comes with it and what its trainers teach up to there */
                climber_skill?: number | null;
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RankResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_selection_api_selection_put: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectionModel"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_status_api_status_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Status"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_time_api_time_get: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_time_api_time_put: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TimeSettingsIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TimeSettings"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_uploads_api_uploads_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadOut"][];
                };
            };
        };
    };
    post_upload_api_uploads_post: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_post_upload_api_uploads_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_paste_api_uploads_paste_post: {
        parameters: {
            query: {
                /** @description which game's data: tbc or forever */
                game_version: "tbc" | "forever";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PasteRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UploadResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_versions_api_versions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionOut"][];
                };
            };
        };
    };
}
